# 自定义层

构造一个没有任何参数的自定义层

In [2]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

将层作为组件合并到构建更复杂的模型中

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(1.8626e-09, grad_fn=<MeanBackward0>)

带参数的图层

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[ 1.6988,  1.3148,  0.8946],
        [ 0.3765, -0.7007,  0.5333],
        [ 1.7925,  0.9664,  0.4432],
        [ 0.5188,  0.8683, -0.0593],
        [-0.4915,  0.8426, -0.6503]], requires_grad=True)

使用自定义层直接执行正向传播计算

In [7]:
dense(torch.rand(2, 5))

tensor([[1.4744, 2.4017, 0.3813],
        [1.5047, 1.2549, 0.6754]])

使用自定义层构建模型

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])